
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NAME NUMBER PRINT SETstatement : SET NAME NUMBERstatement : PRINT NAME'
    
_lr_action_items = {'SET':([0,],[2,]),'PRINT':([0,],[3,]),'$end':([1,5,6,],[0,-2,-1,]),'NAME':([2,3,],[4,5,]),'NUMBER':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> SET NAME NUMBER','statement',3,'p_statement_assign','main.py',39),
  ('statement -> PRINT NAME','statement',2,'p_statement_print','main.py',43),
]
